import { Component,OnInit  } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-gallery',
  imports: [],
  templateUrl: './gallery.html',
  styleUrl: './gallery.css'
})
export class Gallery implements OnInit {
  currentPage = 1;

  pages = [
    {
      id: 1,
      images: [
        '/assets/img/gallery/1.jpg',
        '/assets/img/gallery/2.jpg',
        '/assets/img/gallery/3.jpg',
        '/assets/img/gallery/4.jpg',
        '/assets/img/gallery/5.jpg',
        '/assets/img/gallery/6.jpg',
        '/assets/img/gallery/7.jpg',
        '/assets/img/gallery/8.jpg',
        '/assets/img/gallery/9.jpg',
        '/assets/img/gallery/10.jpg',
      ],
    },
    {
      id: 2,
      images: [
        '/assets/img/gallery/11.jpg',
        '/assets/img/gallery/12.jpg',
        '/assets/img/gallery/13.jpg',
        '/assets/img/gallery/14.jpg',
        '/assets/img/gallery/15.jpg',
        '/assets/img/gallery/16.jpg',
        '/assets/img/gallery/17.jpg',
        '/assets/img/gallery/18.jpg',
        '/assets/img/gallery/19.jpg',
        '/assets/img/gallery/20.jpg',
      ],
    },
    {
      id: 3,
      images: [
        '/assets/img/gallery/21.jpg',
        '/assets/img/gallery/22.jpg',
        '/assets/img/gallery/23.jpg',
        '/assets/img/gallery/24.jpg',
        '/assets/img/gallery/25.jpg',
        '/assets/img/gallery/26.jpg',
        '/assets/img/gallery/27.jpg',
        '/assets/img/gallery/28.jpg',
        '/assets/img/gallery/29.jpg',
        '/assets/img/gallery/30.jpg',
      ],
    },
    {
      id: 4,
      images: [
        '/assets/img/gallery/31.jpg',
        '/assets/img/gallery/32.jpg',
        '/assets/img/gallery/33.jpg',
        '/assets/img/gallery/34.jpg',
        '/assets/img/gallery/35.jpg',
        '/assets/img/gallery/36.jpg',
        '/assets/img/gallery/37.jpg',
        '/assets/img/gallery/38.jpg',
        '/assets/img/gallery/39.jpg',
        '/assets/img/gallery/40.jpg',
      ],
    },
    {
      id: 5,
      images: [
        '/assets/img/gallery/41.jpg',
        '/assets/img/gallery/42.jpg',
        '/assets/img/gallery/43.jpg',
        '/assets/img/gallery/44.jpg',
        '/assets/img/gallery/45.jpg',
        '/assets/img/gallery/46.jpg',
        '/assets/img/gallery/47.jpg',
        '/assets/img/gallery/48.jpg',
        '/assets/img/gallery/49.jpg',
        '/assets/img/gallery/50.jpg',
      ],
    },
    {
      id: 6,
      images: [
        '/assets/img/gallery/51.jpg',
        '/assets/img/gallery/52.jpg',
        '/assets/img/gallery/53.jpg',
        '/assets/img/gallery/54.jpg',
        '/assets/img/gallery/55.jpg',
        '/assets/img/gallery/56.jpg',
        '/assets/img/gallery/57.jpg',
        '/assets/img/gallery/58.jpg',
        '/assets/img/gallery/59.jpg',
        '/assets/img/gallery/60.jpg',
      ],
    },
    {
      id: 7,
      images: [
        '/assets/img/gallery/61.jpg',
        '/assets/img/gallery/62.jpg',
        '/assets/img/gallery/63.jpg',
        '/assets/img/gallery/64.jpg',
        '/assets/img/gallery/65.jpg',
        '/assets/img/gallery/66.jpg',
        '/assets/img/gallery/67.jpg',
        '/assets/img/gallery/68.jpg',
        '/assets/img/gallery/69.jpg',
        '/assets/img/gallery/70.jpg',
      ],
    },
    {
      id: 8,
      images: [
        '/assets/img/gallery/71.jpg',
        '/assets/img/gallery/72.jpg',
        '/assets/img/gallery/73.jpg',
        '/assets/img/gallery/74.jpg',
        '/assets/img/gallery/75.jpg',
        '/assets/img/gallery/76.jpg',
        '/assets/img/gallery/77.jpg',
        '/assets/img/gallery/78.jpg',
        '/assets/img/gallery/79.jpg',
        '/assets/img/gallery/80.jpg',
      ],
    },
    {
      id: 9,
      images: [
        '/assets/img/gallery/81.jpg',
        '/assets/img/gallery/82.jpg',
        '/assets/img/gallery/83.jpg',
        '/assets/img/gallery/84.jpg',
        '/assets/img/gallery/85.jpg',
        '/assets/img/gallery/86.jpg',
        '/assets/img/gallery/87.jpg',
        '/assets/img/gallery/88.jpg',
        '/assets/img/gallery/89.jpg',
        '/assets/img/gallery/90.jpg',
      ],
    },
    {
      id: 10,
      images: [
        '/assets/img/gallery/91.jpg',
        '/assets/img/gallery/92.jpg',
        '/assets/img/gallery/93.jpg',
        '/assets/img/gallery/94.jpg',
        '/assets/img/gallery/95.jpg',
        '/assets/img/gallery/96.jpg',
        '/assets/img/gallery/97.jpg',
        '/assets/img/gallery/98.jpg',
        '/assets/img/gallery/99.jpg',
        '/assets/img/gallery/100.jpg',
      ],
    },
    {
      id: 11,
      images: [
        '/assets/img/gallery/101.jpg',
        '/assets/img/gallery/102.jpg',
        '/assets/img/gallery/103.jpg',
        '/assets/img/gallery/104.jpg',
        '/assets/img/gallery/105.jpg',
        '/assets/img/gallery/106.jpg',
        '/assets/img/gallery/107.jpg',
        '/assets/img/gallery/108.jpg',
        '/assets/img/gallery/109.jpg',
        '/assets/img/gallery/110.jpg',
      ],
    },
    {
      id: 12,
      images: [
        '/assets/img/gallery/111.jpg',
        '/assets/img/gallery/112.jpg',
        '/assets/img/gallery/113.jpg',
        '/assets/img/gallery/114.jpg',
        '/assets/img/gallery/115.jpg',
        '/assets/img/gallery/116.jpg',
        '/assets/img/gallery/117.jpg',
        '/assets/img/gallery/118.jpg',
        '/assets/img/gallery/119.jpg',
        '/assets/img/gallery/120.jpg',
      ],
    },
    {
      id: 13,
      images: [
        '/assets/img/gallery/121.jpg',
        '/assets/img/gallery/122.jpg',
        '/assets/img/gallery/123.jpg',
        '/assets/img/gallery/124.jpg',
        '/assets/img/gallery/125.jpg',
        '/assets/img/gallery/126.jpg',
        '/assets/img/gallery/127.jpg',
        '/assets/img/gallery/128.jpg',
        '/assets/img/gallery/129.jpg',
        '/assets/img/gallery/130.jpg',
      ],
    },
    {
      id: 14,
      images: [
        '/assets/img/gallery/131.jpg',
        '/assets/img/gallery/132.jpg',
        '/assets/img/gallery/133.jpg',
        '/assets/img/gallery/134.jpg',
        '/assets/img/gallery/135.jpg',
        '/assets/img/gallery/136.jpg',
        '/assets/img/gallery/137.jpg',
        '/assets/img/gallery/138.jpg',
        '/assets/img/gallery/139.jpg',
        '/assets/img/gallery/140.jpg',
      ],
    },
    {
      id: 15,
      images: [
        '/assets/img/gallery/141.jpg',
        '/assets/img/gallery/142.jpg',
        '/assets/img/gallery/143.jpg',
        '/assets/img/gallery/144.jpg',
        '/assets/img/gallery/145.jpg',
        '/assets/img/gallery/146.jpg',
        '/assets/img/gallery/147.jpg',
        '/assets/img/gallery/148.jpg',
        '/assets/img/gallery/149.jpg',
        '/assets/img/gallery/150.jpg',
      ],
    },
    {
      id: 16,
      images: [
        '/assets/img/gallery/151.jpg',
        '/assets/img/gallery/152.jpg',
        '/assets/img/gallery/153.jpg',
        '/assets/img/gallery/154.jpg',
        '/assets/img/gallery/155.jpg',
        '/assets/img/gallery/156.jpg',
        '/assets/img/gallery/157.jpg',
        '/assets/img/gallery/158.jpg',
        '/assets/img/gallery/159.jpg',
        '/assets/img/gallery/160.jpg',
      ],
    },
    {
      id: 17,
      images: [
        '/assets/img/gallery/161.jpg',
        '/assets/img/gallery/162.jpg',
        '/assets/img/gallery/163.jpg',
        '/assets/img/gallery/164.jpg',
        '/assets/img/gallery/165.jpg',
        '/assets/img/gallery/166.jpg',
        '/assets/img/gallery/167.jpg',
        '/assets/img/gallery/168.jpg',
        '/assets/img/gallery/169.jpg',
        '/assets/img/gallery/170.jpg',
      ],
    },
    {
      id: 18,
      images: [
        '/assets/img/gallery/171.jpg',
        '/assets/img/gallery/172.jpg',
        '/assets/img/gallery/173.jpg',
        '/assets/img/gallery/174.jpg',
        '/assets/img/gallery/175.jpg',
        '/assets/img/gallery/176.jpg',
        '/assets/img/gallery/177.jpg',
        '/assets/img/gallery/178.jpg',
        '/assets/img/gallery/179.jpg',
        '/assets/img/gallery/180.jpg',
      ],
    },
    {
      id: 19,
      images: [
        '/assets/img/gallery/181.jpg',
        '/assets/img/gallery/182.jpg',
        '/assets/img/gallery/183.jpg',
        '/assets/img/gallery/184.jpg',
        '/assets/img/gallery/185.jpg',
        '/assets/img/gallery/186.jpg',
        '/assets/img/gallery/187.jpg',
        '/assets/img/gallery/188.jpg',
        '/assets/img/gallery/189.jpg',
        '/assets/img/gallery/190.jpg',
      ],
    },
    {
      id: 20,
      images: [
        '/assets/img/gallery/191.jpg',
        '/assets/img/gallery/192.jpg',
        '/assets/img/gallery/193.jpg',
        '/assets/img/gallery/194.jpg',
        '/assets/img/gallery/195.jpg',
        '/assets/img/gallery/196.jpg',
        '/assets/img/gallery/197.jpg',
        '/assets/img/gallery/198.jpg',
        '/assets/img/gallery/199.jpg',
        '/assets/img/gallery/200.jpg',
      ],
    },
    {
      id: 21,
      images: [
        '/assets/img/gallery/201.jpg',
        '/assets/img/gallery/202.jpg',
        '/assets/img/gallery/203.jpg',
        '/assets/img/gallery/204.jpg',
        '/assets/img/gallery/205.jpg',
        '/assets/img/gallery/206.jpg',
        '/assets/img/gallery/207.jpg',
        '/assets/img/gallery/208.jpg',
        '/assets/img/gallery/209.jpg',
        '/assets/img/gallery/210.jpg',
      ],
    },
    {
      id: 22,
      images: [
        '/assets/img/gallery/211.jpg',
        '/assets/img/gallery/212.jpg',
        '/assets/img/gallery/213.jpg',
        '/assets/img/gallery/214.jpg',
        '/assets/img/gallery/215.jpg',
        '/assets/img/gallery/216.jpg',
        '/assets/img/gallery/217.jpg',
        '/assets/img/gallery/218.jpg',
        '/assets/img/gallery/219.jpg',
        '/assets/img/gallery/220.jpg',
      ],
    },
    {
      id: 23,
      images: [
        '/assets/img/gallery/221.jpg',
        '/assets/img/gallery/222.jpg',
        '/assets/img/gallery/223.jpg',
        '/assets/img/gallery/224.jpg',
        '/assets/img/gallery/225.jpg',
        '/assets/img/gallery/226.jpg',
        '/assets/img/gallery/227.jpg',
        '/assets/img/gallery/228.jpg',
        '/assets/img/gallery/229.jpg',
        '/assets/img/gallery/230.jpg',
      ],
    },
    {
      id: 24,
      images: [
        '/assets/img/gallery/231.jpg',
        '/assets/img/gallery/232.jpg',
        '/assets/img/gallery/233.jpg',
        '/assets/img/gallery/234.jpg',
        '/assets/img/gallery/235.jpg',
        '/assets/img/gallery/236.jpg',
        '/assets/img/gallery/237.jpg',
        '/assets/img/gallery/238.jpg',
        '/assets/img/gallery/239.jpg',
        '/assets/img/gallery/240.jpg',
      ],
    },
    {
      id: 25,
      images: [
        '/assets/img/gallery/241.jpg',
        '/assets/img/gallery/242.jpg',
        '/assets/img/gallery/243.jpg',
        '/assets/img/gallery/244.jpg',
        '/assets/img/gallery/245.jpg',
        '/assets/img/gallery/246.jpg',
        '/assets/img/gallery/247.jpg',
        '/assets/img/gallery/248.jpg',
        '/assets/img/gallery/249.jpg',
        '/assets/img/gallery/250.jpg',
      ],
    },
    {
      id: 26,
      images: [
        '/assets/img/gallery/251.jpg',
        '/assets/img/gallery/252.jpg',
        '/assets/img/gallery/253.jpg',
        '/assets/img/gallery/254.jpg',
        '/assets/img/gallery/255.jpg',
        '/assets/img/gallery/256.jpg',
        '/assets/img/gallery/257.jpg',
        '/assets/img/gallery/258.jpg',
        '/assets/img/gallery/259.jpg',
        '/assets/img/gallery/260.jpg',
      ],
    },
    {
      id: 27,
      images: [
        '/assets/img/gallery/261.jpg',
        '/assets/img/gallery/262.jpg',
        '/assets/img/gallery/263.jpg',
        '/assets/img/gallery/264.jpg',
        '/assets/img/gallery/265.jpg',
        '/assets/img/gallery/266.jpg',
        '/assets/img/gallery/267.jpg',
        '/assets/img/gallery/268.jpg',
        '/assets/img/gallery/269.jpg',
        '/assets/img/gallery/270.jpg',
      ],
    },
    {
      id: 28,
      images: [
        '/assets/img/gallery/271.jpg',
        '/assets/img/gallery/272.jpg',
        '/assets/img/gallery/273.jpg',
        '/assets/img/gallery/274.jpg',
        '/assets/img/gallery/275.jpg',
        '/assets/img/gallery/276.jpg',
        '/assets/img/gallery/277.jpg',
        '/assets/img/gallery/278.jpg',
        '/assets/img/gallery/279.jpg',
        '/assets/img/gallery/280.jpg',
      ],
    },
    {
      id: 29,
      images: [
        '/assets/img/gallery/281.jpg',
        '/assets/img/gallery/282.jpg',
        '/assets/img/gallery/283.jpg',
        '/assets/img/gallery/284.jpg',
        '/assets/img/gallery/285.jpg',
        '/assets/img/gallery/286.jpg',
        '/assets/img/gallery/287.jpg',
        '/assets/img/gallery/288.jpg',
        '/assets/img/gallery/289.jpg',
        '/assets/img/gallery/290.jpg',
      ],
    },
    {
      id: 30,
      images: [
        '/assets/img/gallery/291.jpg',
        '/assets/img/gallery/292.jpg',
        '/assets/img/gallery/293.jpg',
        '/assets/img/gallery/294.jpg',
        '/assets/img/gallery/295.jpg',
        '/assets/img/gallery/296.jpg',
        '/assets/img/gallery/297.jpg',
        '/assets/img/gallery/298.jpg',
        '/assets/img/gallery/299.jpg',
        '/assets/img/gallery/300.jpg',
      ],
    },
    {
      id: 31,
      images: [
        '/assets/img/gallery/301.jpg',
        '/assets/img/gallery/302.jpg',
        '/assets/img/gallery/303.jpg',
        '/assets/img/gallery/304.jpg',
        '/assets/img/gallery/305.jpg',
        '/assets/img/gallery/306.jpg',
        '/assets/img/gallery/307.jpg',
        '/assets/img/gallery/308.jpg',
        '/assets/img/gallery/309.jpg',
        '/assets/img/gallery/310.jpg',
      ],
    },
    {
      id: 32,
      images: [
        '/assets/img/gallery/311.jpg',
        '/assets/img/gallery/312.jpg',
        '/assets/img/gallery/313.jpg',
        '/assets/img/gallery/314.jpg',
        '/assets/img/gallery/315.jpg',
        '/assets/img/gallery/316.jpg',
        '/assets/img/gallery/317.jpg',
        '/assets/img/gallery/318.jpg',
        '/assets/img/gallery/319.jpg',
        '/assets/img/gallery/320.jpg',
      ],
    },
    {
      id: 33,
      images: [
        '/assets/img/gallery/321.jpg',
        '/assets/img/gallery/322.jpg',
        '/assets/img/gallery/323.jpg',
        '/assets/img/gallery/324.jpg',
        '/assets/img/gallery/325.jpg',
        '/assets/img/gallery/326.jpg',
        '/assets/img/gallery/327.jpg',
        '/assets/img/gallery/328.jpg',
        // '/assets/img/gallery/329.jpg',
        // '/assets/img/gallery/330.jpg',
      ],
    },
    // more pages...
  ];
  constructor(private route: ActivatedRoute, private router: Router) {}
  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      const pageParam = Number(params.get('page'));
      if (pageParam && pageParam >= 1 && pageParam <= this.pages.length) {
        this.currentPage = pageParam;
      } else {
        this.router.navigate(['/gallery', 1]);
      }
    });
  }
  get currentImages() {
    return this.pages.find((p) => p.id === this.currentPage)?.images || [];
  }

  totalPages() {
    return this.pages.length;
  }

  pageChanged(page: number) {
    this.router.navigate(['/gallery', page]);
  }
}
